name: Deploy to Railway and Send Slack notification

on:
  push:
    branches: 
    - 'release/v[0-9]+.[0-9]+'
    

jobs:
  deploy:
    if: ${{ !startsWith(github.event.head_commit.message, '#NORUN') }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Railway Deploy
      uses: bervProject/railway-deploy@main
      with:
        railway_token: ${{ secrets.RAILWAY_TOKEN }}
        service: "delicate-lumber"
        
    - name: Get deployment URL
      run: echo "DEPLOYMENT_URL=$(up url -n delicate-lumber )" >> $GITHUB_ENV

    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        # For posting a rich message using Block Kit
        payload: |
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "DipSA 56 CI/CD Submission",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Name:* Su Latt Sandi"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Email*: e1114083@u.nus.edu"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Matriculation:* A0269744M"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Repository:* \n https://github.com/${{ github.repository }}"
                  }
                ]
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Deployment URL:* https://$DEPLOYMENT_URL"
                },
                "accessory": {
                  "type": "button",
                  "text": {
                    "type": "plain_text",
                    "text": "Go",
                    "emoji": true
                  },
                  "value": "click_me_123",
                  "url": "https://$DEPLOYMENT_URL",
                  "action_id": "button-action"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_ME }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK


    
      
   

      




      
    


