name: Deploy to Railway

on:
  push:
    branches: 
    - 'release/v[0-9]+.[0-9]+'
    

jobs:
  deploy:
    if: ${{ !startsWith(github.event.head_commit.message, '#NORUN') }}
    runs-on: ubuntu-latest
    steps:
    - name: Railway Deploy
      uses: bervProject/railway-deploy@main
      with:
        railway_token: ${{ secrets.RAILWAY_TOKEN }}
        service: "delicate-lumber"


