name: Deploy to Railway

on:
  push:
    branches: 
    - release
    tags:
    - 'v+[0-9]+.[0-9]'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

