name: Deploy to Railway


on:
  push:
    branches: 
    - 'release/v[0-9].[0-9]'
    # tags:
    # - 'v+[0-9]+.[0-9]'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Railway Deploy
      uses: bervProject/railway-deploy@0.1.2-beta
      run: railway up
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}


    # - name: Deploy
    #   run: railway up
    #   env:
    #     RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

